### ISSUE TITLE
Widgets signals and slots

### ISSUE THREAD

**Issue by shujaatak** [pierrebai/QWidgetListWidget#1]
I need label and two push buttons(edit, delete) in each list item, can you please mention how I would get and recognize the signals from those two buttons please?

**Comment by pierrebai** [comment]
Hi,

You created the buttons, so you should have access to the variables containing the button pointers. You can call connect with each button and connect the function to handle the signal you want. How to connect signal o handler is explained in Qt documentation.

--
Pierre
________________________________
De : Shujaat Ali Khan <notifications@github.com>
Envoyé : 18 juin 2020 17:26
À : pierrebai/QWidgetListWidget <QWidgetListWidget@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [pierrebai/QWidgetListWidget] Widgets signals and slots (#1)


I need label and two push buttons(edit, delete) in each list item, can you please mention how I would get and recognize the signals from those two buttons please?

**Comment by shujaatak** [comment]
Thanks managed to do it.
